// GET
export const GET_SERVICES = 'GET_SERVICES';
export const GROUPED_USERS_COUNT = 'GROUPED_USERS_COUNT';
export const GET_ORDERS_COUNT = 'GET_ORDERS_COUNT';
export const GET_USERS = 'GET_USERS';
export const GET_AGENT_AVAILABILITY_BY_ID = 'GET_AGENT_AVAILABILITY_BY_ID';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTIONS_BY_USER = 'GET_TRANSACTIONS_BY_USER';
export const GET_BALANCE_DETAIL = 'GET_BALANCE_DETAIL';
export const GET_AGENT_BALANCE_DETAIL = 'GET_AGENT_BALANCE_DETAIL';
export const GET_REVENUE_BY_PERIOD = 'GET_REVENUE_BY_PERIOD';

// POST
export const AUTHENTICATE = 'AUTHENTICATE';
export const SET_USER_STATUS = 'SET_USER_STATUS';
